import type { Product } from "./products"

export const enCategories = [
  { slug: "seal-rings", name: "Carbon Graphite Seal Rings" },
  { slug: "carbon-graphite-sleeves", name: "Carbon Graphite Bushings & Bearings" },
  { slug: "three-part-rings", name: "Carbon Graphite Split Rings" },
]

const enCategorySlugMap: Record<string, string> = {
  "碳石墨密封环": "seal-rings",
  "碳石墨轴套": "carbon-graphite-sleeves",
  "碳石墨三瓣环": "three-part-rings",
}

export function getEnCategoryCounts() {
  const counts: Record<string, number> = {}
  enProducts.forEach((p) => {
    const catSlug = enCategorySlugMap[p.category] || ""
    counts[catSlug] = (counts[catSlug] || 0) + 1
  })
  return counts
}

export function getEnProductBySlug(slug: string): Product | undefined {
  return enProducts.find((p) => p.slug === slug)
}

export function getEnProductsByCategory(categorySlug: string): Product[] {
  return enProducts.filter((p) => (enCategorySlugMap[p.category] || "") === categorySlug)
}

export const enProducts: Product[] = [
  {
    slug: "bia-series",
    name: "BIA Carbon Graphite Seal Ring",
    model: "BIA Series",
    category: "碳石墨密封环",
    description:
      "The BIA series carbon graphite seal ring is designed for high-temperature, high-speed rotating equipment. Advanced material formulation provides excellent dimensional stability and consistent sealing performance under demanding conditions.",
    shortDesc: "High-temp carbon graphite seal ring for demanding rotating equipment.",
    specs: [
      { label: "Model", value: "BIA" },
      { label: "Temperature", value: "-40°C ~ 280°C" },
      { label: "Pressure", value: "≤ 0.8 MPa" },
      { label: "Speed", value: "≤ 5000 rpm" },
      { label: "Material", value: "Impregnated Carbon Graphite" },
      { label: "Application", value: "Rotating shafts, agitators" },
    ],
    commonSizes: [
      { label: "Inner Dia (d)", value: "12 ~ 100 mm" },
      { label: "Outer Dia (D)", value: "24 ~ 130 mm" },
      { label: "Height (H)", value: "6 ~ 20 mm" },
      { label: "Seal Face Width", value: "3 ~ 8 mm" },
    ],
    matingMaterials: ["Silicon Carbide (SiC)", "Tungsten Carbide (WC)", "Alumina Ceramic (Al₂O₃)", "High-Chrome Stainless Steel"],
    installationNotes: [
      "Inspect seal face for scratches or chips before installation; clean with lint-free cloth and alcohol",
      "Verify bushing-to-shaft clearance is within recommended range",
      "Use a dedicated installation guide sleeve; apply even press force at 2~5 mm/s",
      "Hand-rotate 2~3 turns after installation to confirm free rotation",
      "Follow break-in procedure: first 30 min at ≤ 50% rated speed",
    ],
    applications: ["Agitators", "Mixers", "Compressors", "High-Speed Rotors"],
    materials: ["Standard Graphite", "Resin-Impregnated Graphite", "Antimony-Impregnated Graphite", "Copper-Impregnated Graphite"],
    features: [
      "Excellent high-temperature stability",
      "Anti-oxidation treatment extends service life",
      "Low friction coefficient",
      "Self-lubricating during start-up and shutdown",
      "Outstanding chemical resistance",
    ],
    faq: [
      { q: "What is the maximum operating temperature of the BIA series?", a: "The BIA series with anti-oxidation impregnation can operate continuously at 280°C, with short-term peaks up to 350°C." },
    ],
    image: "/images/products/catalog/bia.jpg",
  },
  {
    slug: "104-series",
    name: "104 Carbon Graphite Seal Ring",
    model: "104 Series",
    category: "碳石墨密封环",
    description:
      "The 104 series carbon graphite seal ring is a compact high-performance sealing solution designed for space-constrained installations. Optimized geometry provides excellent sealing force distribution while minimizing axial space requirements.",
    shortDesc: "Compact carbon graphite seal ring for tight installations.",
    specs: [
      { label: "Model", value: "104" },
      { label: "Material", value: "Carbon Graphite" },
      { label: "Temperature", value: "-20°C ~ 200°C" },
      { label: "Pressure", value: "≤ 0.8 MPa" },
      { label: "Speed", value: "≤ 3500 rpm" },
    ],
    commonSizes: [
      { label: "Inner Dia (d)", value: "8 ~ 60 mm" },
      { label: "Outer Dia (D)", value: "20 ~ 80 mm" },
      { label: "Height (H)", value: "5 ~ 14 mm" },
    ],
    matingMaterials: ["Silicon Carbide (SiC)", "Tungsten Carbide (WC)", "High-Chrome Stainless Steel", "Hardened Tool Steel"],
    installationNotes: [
      "Confirm size match before installation; wipe seal face with clean cloth",
      "The 104 series has compact axial space; ensure spring compression is properly adjusted",
      "Housing chamfer should be ≥ 15° to avoid O.D. scoring during pressing",
      "Apply steady, even press force; use a press rather than hammer installation",
      "Check leakage and temperature during initial run; stabilizes after 2-hour break-in",
    ],
    applications: ["Small Pumps", "Automotive", "Home Appliances", "Light Industry"],
    materials: ["Standard Graphite", "Resin-Impregnated Graphite", "Antimony-Impregnated Graphite", "Copper-Impregnated Graphite"],
    features: [
      "Compact axial design",
      "Cost-effective for high-volume applications",
      "Reliable sealing performance",
      "Easy replacement",
    ],
    faq: [
      { q: "Is the 104 series suitable for high-volume OEM applications?", a: "Yes, the 104 series is designed for cost-effective batch production, offering consistent quality ideal for space-constrained OEM applications." },
    ],
    image: "/images/products/catalog/104.jpg",
  },
  {
    slug: "109-series",
    name: "109 Carbon Graphite Seal Ring",
    model: "109 Series",
    category: "碳石墨密封环",
    description: "The 109 series is one of the most widely used general mechanical seal ring models, suitable for centrifugal pumps handling clean fluids, water pumps, and wastewater pumps. Standardized dimensions make replacement easy with reliable, stable performance.",
    shortDesc: "General-purpose carbon graphite seal ring for clean fluid centrifugal pumps.",
    specs: [
      { label: "Model", value: "109" },
      { label: "Temperature", value: "-20°C ~ 180°C" },
      { label: "Pressure", value: "≤ 1.0 MPa" },
      { label: "Speed", value: "≤ 4000 rpm" },
      { label: "Medium", value: "Clean water, wastewater, light oil" },
    ],
    commonSizes: [
      { label: "Inner Dia (d)", value: "10 ~ 80 mm" },
      { label: "Outer Dia (D)", value: "22 ~ 100 mm" },
      { label: "Height (H)", value: "6 ~ 18 mm" },
    ],
    matingMaterials: ["Silicon Carbide (SiC)", "Tungsten Carbide (WC)", "Stainless Steel (304/316)", "Ceramic"],
    installationNotes: [
      "Versatile 109 series; confirm size matches pump shaft before installation",
      "Never bump the seal face; even a small chip can cause leakage",
      "Check spring compression after spring seat installation",
      "Pump shaft radial runout should be ≤ 0.05 mm; align shaft if exceeded",
      "Install inlet filter if medium contains particles to protect seal face",
    ],
    applications: ["Centrifugal Pumps", "Water Pumps", "Wastewater Pumps", "General Industry"],
    materials: ["Standard Graphite", "Resin-Impregnated Graphite", "Antimony-Impregnated Graphite", "Copper-Impregnated Graphite"],
    features: ["Most versatile, widely used", "Standardized dimensions, easy replacement", "Stable and reliable performance", "Excellent cost-performance ratio"],
    faq: [],
    image: "/images/products/catalog/109.jpg",
  },
  {
    slug: "58u-series",
    name: "58U Carbon Graphite Seal Ring",
    model: "58U Series",
    category: "碳石墨密封环",
    description: "The 58U series features an unbalanced design suitable for low to medium pressure rotating equipment sealing. Compact structure with easy installation, widely used in conventional industrial pumps and agitators.",
    shortDesc: "Unbalanced carbon graphite seal ring for low-medium pressure.",
    specs: [
      { label: "Model", value: "58U" },
      { label: "Temperature", value: "-20°C ~ 200°C" },
      { label: "Pressure", value: "≤ 0.8 MPa" },
      { label: "Speed", value: "≤ 3000 rpm" },
    ],
    commonSizes: [
      { label: "Inner Dia (d)", value: "16 ~ 80 mm" },
      { label: "Outer Dia (D)", value: "28 ~ 100 mm" },
      { label: "Height (H)", value: "8 ~ 20 mm" },
    ],
    matingMaterials: ["Silicon Carbide (SiC)", "Tungsten Carbide (WC)", "Stainless Steel", "Ceramic"],
    installationNotes: [
      "58U is unbalanced type; note medium pressure direction marking during installation",
      "Clean housing bore, check for burrs; ensure smooth chamfer",
      "Use dedicated pressing tool for seal ring installation; never hammer",
      "Spring compression must be even after installation; check all springs for equal height",
      "Hand-rotate before start-up to confirm free movement",
    ],
    applications: ["Industrial Pumps", "Agitators", "Mixers", "Light Equipment"],
    materials: ["Standard Graphite", "Resin-Impregnated Graphite", "Antimony-Impregnated Graphite", "Copper-Impregnated Graphite"],
    features: ["Unbalanced design", "Compact structure", "Easy installation", "Economical"],
    faq: [],
    image: "/images/products/catalog/58u.jpg",
  },
  {
    slug: "m7n-series",
    name: "M7N Carbon Graphite Seal Ring",
    model: "M7N Series",
    category: "碳石墨密封环",
    description: "The M7N series is designed for the chemical industry with excellent chemical corrosion resistance. Multi-spring structure provides strong compensation capability, suitable for chemical pumps and reactor agitators handling particle-containing media.",
    shortDesc: "Chemical-grade carbon graphite seal ring, corrosion-resistant multi-spring design.",
    specs: [
      { label: "Model", value: "M7N" },
      { label: "Temperature", value: "-30°C ~ 220°C" },
      { label: "Pressure", value: "≤ 1.5 MPa" },
      { label: "Speed", value: "≤ 3500 rpm" },
      { label: "Medium", value: "Chemicals, acids, alkalis, solvents" },
    ],
    commonSizes: [
      { label: "Inner Dia (d)", value: "18 ~ 100 mm" },
      { label: "Outer Dia (D)", value: "32 ~ 130 mm" },
      { label: "Height (H)", value: "10 ~ 25 mm" },
    ],
    matingMaterials: ["Silicon Carbide (SiC)", "Tungsten Carbide (WC)", "Alumina Ceramic (Al₂O₃)"],
    installationNotes: [
      "M7N multi-spring design: ensure all springs are at equal height to prevent uneven loading",
      "Chemical media can be aggressive; confirm O-ring material compatibility",
      "Purge air from seal cavity before start-up to prevent dry running",
      "For particle-containing media, consider seal face groove design for particle evacuation",
      "Flush seal cavity after shutdown to prevent crystallization or deposit solidification",
    ],
    applications: ["Chemical Pumps", "Reactors", "Agitators", "Pharmaceutical Equipment"],
    materials: ["Standard Graphite", "Resin-Impregnated Graphite", "Antimony-Impregnated Graphite", "Copper-Impregnated Graphite"],
    features: ["Multi-spring design for strong compensation", "Chemical corrosion resistant", "Suitable for particle-containing media", "Stable sealing performance"],
    faq: [],
    image: "/images/products/catalog/m7n.jpg",
  },
  {
    slug: "206-series",
    name: "206 Carbon Graphite Seal Ring",
    model: "206 Series",
    category: "碳石墨密封环",
    description: "The 206 series dual-face mechanical seal carbon graphite ring is suitable for applications requiring flushing or circulation cooling. The dual-face design provides higher sealing safety for hazardous or easily leaked media.",
    shortDesc: "Dual-face mechanical seal carbon graphite ring for hazardous media.",
    specs: [
      { label: "Model", value: "206" },
      { label: "Temperature", value: "-20°C ~ 200°C" },
      { label: "Pressure", value: "≤ 2.0 MPa" },
      { label: "Speed", value: "≤ 3000 rpm" },
    ],
    commonSizes: [
      { label: "Inner Dia (d)", value: "20 ~ 90 mm" },
      { label: "Outer Dia (D)", value: "36 ~ 120 mm" },
      { label: "Height (H)", value: "10 ~ 22 mm" },
    ],
    matingMaterials: ["Silicon Carbide (SiC)", "Tungsten Carbide (WC)", "Stainless Steel"],
    installationNotes: [
      "206 is dual-face seal; ensure flush port orientation is correct during installation",
      "Both seal faces must maintain parallelism ≤ 0.05 mm",
      "Connect flush system piping; circulate fluid to purge air from lines",
      "Adjust cooling fluid flow rate per operating conditions",
      "Monitor buffer fluid pressure during operation; must remain above medium pressure",
    ],
    applications: ["Chemical Pumps", "Hazardous Media Pumps", "High-Pressure Reactors", "Pharmaceutical Equipment"],
    materials: ["Standard Graphite", "Resin-Impregnated Graphite", "Antimony-Impregnated Graphite", "Copper-Impregnated Graphite"],
    features: ["Dual-face design", "High safety", "Suitable for flush systems", "High sealing reliability"],
    faq: [],
    image: "/images/products/catalog/206.jpg",
  },
  {
    slug: "59u-series",
    name: "59U Carbon Graphite Seal Ring",
    model: "59U Series",
    category: "碳石墨密封环",
    description: "The 59U series is an embedded carbon graphite seal ring with rubber bellows design, providing excellent follow-up compensation ability. Suitable for marine pumps, seawater pumps, and various corrosive media conditions.",
    shortDesc: "Embedded carbon graphite seal ring for marine and seawater pumps.",
    specs: [
      { label: "Model", value: "59U" },
      { label: "Temperature", value: "-30°C ~ 180°C" },
      { label: "Pressure", value: "≤ 1.0 MPa" },
      { label: "Speed", value: "≤ 3500 rpm" },
      { label: "Medium", value: "Seawater, fresh water, oils" },
    ],
    commonSizes: [
      { label: "Inner Dia (d)", value: "14 ~ 80 mm" },
      { label: "Outer Dia (D)", value: "26 ~ 100 mm" },
      { label: "Height (H)", value: "8 ~ 20 mm" },
    ],
    matingMaterials: ["Silicon Carbide (SiC)", "Tungsten Carbide (WC)", "High-Chrome Stainless Steel"],
    installationNotes: [
      "59U uses rubber bellows; avoid twisting or deforming bellows during installation",
      "Ensure housing chamfer is smooth to avoid cutting rubber components",
      "Select seawater-resistant impregnation grade for marine applications",
      "Rubber bellows are temperature-sensitive; keep medium temperature within rating",
      "Hand-rotate after installation to check for bellows interference",
    ],
    applications: ["Marine Pumps", "Seawater Pumps", "Cooling Water Pumps", "General Industry"],
    materials: ["Standard Graphite", "Resin-Impregnated Graphite", "Antimony-Impregnated Graphite", "Copper-Impregnated Graphite"],
    features: ["Rubber bellows design", "Good follow-up compensation", "Seawater corrosion resistant", "Easy installation"],
    faq: [],
    image: "/images/products/catalog/59u.jpg",
  },
  {
    slug: "58b-series",
    name: "58B Carbon Graphite Seal Ring",
    model: "58B Series",
    category: "碳石墨密封环",
    description: "The 58B series is a medium-duty mechanical seal ring with balanced design capable of handling higher pressures. Suitable for demanding applications such as power plant circulating water pumps and large industrial pumps.",
    shortDesc: "Balanced carbon graphite seal ring for medium-high pressure.",
    specs: [
      { label: "Model", value: "58B" },
      { label: "Temperature", value: "-20°C ~ 200°C" },
      { label: "Pressure", value: "≤ 2.0 MPa" },
      { label: "Speed", value: "≤ 4000 rpm" },
    ],
    commonSizes: [
      { label: "Inner Dia (d)", value: "20 ~ 100 mm" },
      { label: "Outer Dia (D)", value: "36 ~ 130 mm" },
      { label: "Height (H)", value: "10 ~ 24 mm" },
    ],
    matingMaterials: ["Silicon Carbide (SiC)", "Tungsten Carbide (WC)", "Stainless Steel"],
    installationNotes: [
      "58B is a balanced design with high pressure capacity; confirm pressure rating before installation",
      "Balanced design requires precise alignment; shaft runout ≤ 0.04 mm",
      "Ensure seal cavity is adequately cooled before start-up to avoid thermal shock",
      "Tighten bolts to recommended torque in 2~3 stages diagonally",
      "Monitor temperature and leakage during initial run; stabilize before loading",
    ],
    applications: ["Circulating Water Pumps", "Large Industrial Pumps", "Power Plant Equipment", "Water Supply Systems"],
    materials: ["Standard Graphite", "Resin-Impregnated Graphite", "Antimony-Impregnated Graphite", "Copper-Impregnated Graphite"],
    features: ["Balanced design", "High pressure capacity", "Suitable for high-speed conditions", "Excellent durability"],
    faq: [],
    image: "/images/products/catalog/58b.jpg",
  },
  {
    slug: "graphite-bushing",
    name: "Graphite Bushing",
    model: "SB Series",
    category: "碳石墨轴套",
    description:
      "Graphite bushings (carbon graphite sleeves) are made from high-quality carbon graphite material with excellent self-lubricating properties, temperature resistance, and corrosion resistance. Suitable for supporting and guiding rotating or reciprocating motion components in oil-free or boundary lubrication conditions. Widely used in submersible pumps, wastewater pumps, chemical pumps, and various industrial pumps, operating stably in water, oil, and various chemical media. Custom non-standard sizes supported per drawing.",
    shortDesc: "Self-lubricating carbon graphite bushing, high-temp & corrosion resistant for pumps and underwater equipment.",
    specs: [
      { label: "Model", value: "SB100 / SB200 / SB300 (custom per drawing)" },
      { label: "Temperature", value: "-50°C ~ 300°C (anti-oxidation to 350°C)" },
      { label: "Pressure", value: "≤ 15 MPa" },
      { label: "Speed", value: "≤ 20 m/s" },
      { label: "Medium", value: "Clean water, wastewater, seawater, oils, mild acids/alkalis, organic solvents" },
      { label: "Material Grade", value: "M126D / M204K / M254K, etc." },
    ],
    applications: ["Submersible Pumps", "Wastewater Pumps", "Chemical Pumps", "Valves", "Hydraulic Equipment"],
    materials: ["Standard Graphite", "Resin-Impregnated Graphite", "Antimony-Impregnated Graphite", "Copper-Impregnated Graphite"],
    features: [
      "Excellent self-lubrication, operates in dry or boundary lubrication conditions",
      "Wide temperature range; anti-oxidation grades withstand 350°C peak",
      "Strong chemical inertness, resists acids, alkalis, and organic solvents",
      "Good dimensional stability, low thermal expansion for precision fits",
      "Custom non-standard sizes and shapes per customer drawing",
      "Low friction coefficient, reduces mating part wear, extends equipment life",
    ],
    faq: [
      { q: "Do graphite bushings require oil lubrication?", a: "No. Carbon graphite has natural self-lubricating properties and operates normally in oil-free conditions. However, auxiliary lubrication can further extend service life when conditions permit." },
      { q: "Can you customize bushings per drawing?", a: "Absolutely. We have mature custom manufacturing capabilities supporting drawing-based processing. Provide detailed dimensional drawings or samples, and our engineers will respond within 24 hours." },
    ],
    image: "/images/products/graphite-bushing.png",
  },
  {
    slug: "graphite-bearing",
    name: "Graphite Bearing",
    model: "GB Series",
    category: "碳石墨轴套",
    description:
      "Graphite bearings are made from high-strength carbon graphite material, designed for rotating equipment that承受s higher radial loads. Excellent self-lubricating properties make them particularly suitable for applications where grease lubrication is impossible or maintenance is difficult. Widely used in marine stern shaft bearings, pump bearings, agitator bearings, and various industrial machinery, operating stably in water, oil, and various chemical media.",
    shortDesc: "High-strength self-lubricating graphite bearing for heavy-load rotating equipment.",
    specs: [
      { label: "Model", value: "GB100 / GB200 / GB300 (custom per drawing)" },
      { label: "Temperature", value: "-50°C ~ 300°C (anti-oxidation to 350°C)" },
      { label: "Pressure", value: "≤ 20 MPa" },
      { label: "Speed", value: "≤ 15 m/s" },
      { label: "Medium", value: "Clean water, seawater, oils, mild acids/alkalis, organic solvents" },
      { label: "Material Grade", value: "M204K / M254K / M126D, etc." },
    ],
    applications: ["Marine Stern Shaft", "Agitators", "Chemical Pumps", "Compressors", "Mining Equipment"],
    materials: ["Standard Graphite", "Resin-Impregnated Graphite", "Antimony-Impregnated Graphite", "Copper-Impregnated Graphite"],
    features: [
      "High load capacity for heavy-duty rotating applications",
      "Natural self-lubrication, no external lubrication system needed",
      "High temperature and corrosion resistance for harsh environments",
      "Maintains good lubrication during start-up and shutdown",
      "Custom dimensions and tolerances per drawing",
      "Quiet, smooth operation, reducing equipment vibration",
    ],
    faq: [
      { q: "What load can graphite bearings handle?", a: "GB series graphite bearings can handle radial loads ranging from 5~20 MPa depending on the grade and impregnation process. Provide specific operating parameters for the best grade recommendation." },
      { q: "Are graphite bearings suitable for seawater?", a: "Yes. Graphite bearings with corrosion-resistant impregnation operate stably long-term in seawater, making them ideal for marine stern shaft and seawater pump bearings." },
    ],
    image: "/images/products/graphite-bearing.png",
  },
  {
    slug: "graphite-thrust-disc",
    name: "Graphite Thrust Disc",
    model: "TD Series",
    category: "碳石墨轴套",
    description:
      "Graphite thrust discs (also called thrust washers or wear plates) are made from high-quality carbon graphite material, specially designed for承受ing axial thrust loads. With excellent wear resistance and self-lubricating properties, they are suitable for axial positioning and load-bearing in vertical pumps, submersible pumps, agitators, and similar equipment. They operate stably long-term in oil-free or boundary lubrication conditions, effectively protecting equipment end faces and preventing metal-to-metal contact.",
    shortDesc: "Wear-resistant self-lubricating graphite thrust disc for axial load-bearing.",
    specs: [
      { label: "Model", value: "TD100 / TD200 / TD300 (custom per drawing)" },
      { label: "Temperature", value: "-40°C ~ 280°C (anti-oxidation to 350°C)" },
      { label: "Axial Load", value: "≤ 10 MPa" },
      { label: "Speed", value: "≤ 15 m/s" },
      { label: "Medium", value: "Clean water, wastewater, oils, chemicals" },
      { label: "Material Grade", value: "M126D / M204K / M254K, etc." },
    ],
    applications: ["Vertical Pumps", "Submersible Pumps", "Agitators", "Centrifugal Pumps", "Hydraulic Equipment"],
    materials: ["Standard Graphite", "Resin-Impregnated Graphite", "Antimony-Impregnated Graphite", "Copper-Impregnated Graphite"],
    features: [
      "Excellent wear resistance, long service life",
      "Self-lubricating, no external oil supply needed",
      "Effectively bears axial thrust, protects equipment end faces",
      "High temperature and corrosion resistance for various conditions",
      "Custom non-standard sizes and thickness per drawing",
      "Easy replacement, low maintenance cost",
    ],
    faq: [
      { q: "What is the difference between a thrust disc and a bearing?", a: "A graphite thrust disc primarily承受s axial thrust loads and is installed on the shaft end face. Graphite bearings primarily承受 radial loads and are installed in the housing bore. Their application scenarios and load directions differ." },
      { q: "Can you customize non-standard thrust disc sizes?", a: "Absolutely. Provide detailed drawings or samples, and we can customize outer diameter, inner diameter, thickness, and mounting hole positions per your requirements." },
    ],
    image: "/images/products/graphite-thrust-disc.png",
  },
  {
    slug: "three-part-series",
    name: "Carbon Graphite Split Ring",
    model: "TP Series",
    category: "碳石墨三瓣环",
    description:
      "Carbon graphite split rings feature a segmented three-part design, composed of three 120° arc segments precision-assembled. The split design facilitates installation in enclosed cavities where shaft-end access is impossible, widely used in compressors, pumps, and various rotating equipment sealing and support applications. The mating surfaces between segments are precision-lapped, achieving overall sealing performance comparable to solid rings.",
    shortDesc: "Segmented three-part carbon graphite ring for enclosed cavity installation.",
    specs: [
      { label: "Model", value: "TP100 / TP200 / TP300 (custom per drawing)" },
      { label: "Temperature", value: "-40°C ~ 280°C (anti-oxidation to 350°C)" },
      { label: "Pressure", value: "≤ 10 MPa" },
      { label: "Speed", value: "≤ 15 m/s" },
      { label: "Medium", value: "Water, oil, chemicals, steam, gas" },
      { label: "Segments", value: "3 segments (120° each); multi-segment custom available" },
    ],
    applications: ["Compressors", "Centrifugal Pumps", "Marine Equipment", "Chemical Equipment", "Steam Turbines"],
    materials: ["Standard Graphite", "Resin-Impregnated Graphite", "Antimony-Impregnated Graphite", "Copper-Impregnated Graphite"],
    features: [
      "Segmented three-part design installs in enclosed cavities without shaft removal",
      "Precision-lapped segment joints for excellent assembled sealing performance",
      "Carbon graphite self-lubrication, no external lubrication needed",
      "High temperature and corrosion resistant for harsh conditions",
      "Custom sizes and segment counts per customer drawing",
      "Easy maintenance, individual damaged segments can be replaced",
    ],
    faq: [
      { q: "What is the difference between split rings and solid rings?", a: "Split rings consist of three assembled segments, offering the advantage of installation in enclosed cavities without shaft removal. Solid rings are one-piece with slightly better sealing but require shaft-end access for installation." },
      { q: "Do the segment joints leak?", a: "Segment joints are precision-lapped. Combined with carbon graphite's self-lubricating properties, the inter-segment gap is minimal during operation. For most conditions, sealing performance fully meets requirements." },
      { q: "Can you customize other segment counts?", a: "Yes. Beyond the standard three-segment design, we can customize 2, 4, 6, or more segments to suit different installation spaces and requirements." },
    ],
    image: "/images/products/three-part-ring.jpg",
  },
  // ===== New products from product catalog =====
  {
    slug: "oil-pump-double-seal",
    name: "Oil Pump Double Mechanical Seal",
    model: "Oil Pump Double Seal Series",
    category: "碳石墨密封环",
    description:
      "The oil pump double mechanical seal features a dual-seal face design, developed specifically for oil pump rotating equipment. Dual-ring coordinated sealing provides higher sealing reliability, effectively preventing oil leakage. Suitable for various industrial oil pumps, hydraulic pumps, and lubrication systems. Made from premium carbon graphite with precision-lapped faces, offering excellent self-lubrication and wear resistance in oil media.",
    shortDesc: "Double mechanical seal for oil pumps, dual-face anti-leak design.",
    specs: [
      { label: "Model", value: "Oil Pump Double Seal (custom per drawing)" },
      { label: "Temperature", value: "-20°C ~ 200°C" },
      { label: "Pressure", value: "≤ 1.0 MPa" },
      { label: "Speed", value: "≤ 3500 rpm" },
      { label: "Medium", value: "Oils, hydraulic fluid, lubricants" },
    ],
    commonSizes: [
      { label: "Inner Dia (d)", value: "12 ~ 80 mm" },
      { label: "Outer Dia (D)", value: "24 ~ 100 mm" },
      { label: "Height (H)", value: "8 ~ 20 mm" },
    ],
    matingMaterials: ["Silicon Carbide (SiC)", "Tungsten Carbide (WC)", "Stainless Steel"],
    installationNotes: [
      "Note relative position and orientation of the two seal faces during installation",
      "Confirm chemical compatibility of oil with sealing materials before installation",
      "Use oil-resistant rubber for O-rings",
      "Use dedicated guide sleeve to ensure concentricity when pressing",
      "Check leakage after initial run; stable operation achievable",
    ],
    applications: ["Oil Pumps", "Hydraulic Pumps", "Lubrication Systems", "Gearboxes"],
    materials: ["Standard Graphite", "Resin-Impregnated Graphite", "Antimony-Impregnated Graphite", "Copper-Impregnated Graphite"],
    features: [
      "Dual seal face design, high reliability",
      "Excellent oil resistance",
      "Self-lubricating, strong dry-start capability",
      "Precision-lapped faces, low leakage",
    ],
    faq: [],
    image: "/images/products/catalog/oil-pump-double-seal.jpg",
  },
  {
    slug: "g6-series",
    name: "G6 Carbon Graphite Seal Ring",
    model: "G6 Series",
    category: "碳石墨密封环",
    description:
      "The G6 carbon graphite seal ring is a standard interchangeable mechanical seal ring compatible with equivalent models from major international brands. Precision-machined seal faces with optimized carbon graphite material formulation deliver stable and reliable performance in clean water, wastewater, and various industrial media.",
    shortDesc: "G6 standard carbon graphite seal ring, interchangeable with major brands.",
    specs: [
      { label: "Model", value: "G6" },
      { label: "Temperature", value: "-20°C ~ 200°C" },
      { label: "Pressure", value: "≤ 0.8 MPa" },
      { label: "Speed", value: "≤ 3500 rpm" },
    ],
    commonSizes: [
      { label: "Inner Dia (d)", value: "10 ~ 80 mm" },
      { label: "Outer Dia (D)", value: "22 ~ 100 mm" },
      { label: "Height (H)", value: "6 ~ 18 mm" },
    ],
    matingMaterials: ["Silicon Carbide (SiC)", "Tungsten Carbide (WC)", "Stainless Steel"],
    installationNotes: [
      "Confirm dimensions match original seal before installation",
      "Gently wipe seal face with lint-free cloth; avoid scratches",
      "Maintain vertical even pressure when pressing",
      "Tighten bolts diagonally in stages",
      "Check leakage and face temperature during initial run",
    ],
    applications: ["Industrial Pumps", "Water Pumps", "Wastewater Pumps", "General Machinery"],
    materials: ["Standard Graphite", "Resin-Impregnated Graphite", "Antimony-Impregnated Graphite", "Copper-Impregnated Graphite"],
    features: ["Standard interchangeable dimensions", "Stable sealing performance", "Multiple impregnation options", "Economical"],
    faq: [],
    image: "/images/products/catalog/g6.jpg",
  },
  {
    slug: "f-type-series",
    name: "F-Type Carbon Graphite Seal Ring",
    model: "F Series",
    category: "碳石墨密封环",
    description:
      "The F-type carbon graphite seal ring features a special structural design for rotating equipment with specific installation space and operating requirements. Compact profile with reliable sealing performance makes it suitable for various industrial pumps and rotating machinery.",
    shortDesc: "F-type carbon graphite seal ring, compact high-performance design.",
    specs: [
      { label: "Model", value: "F-Type" },
      { label: "Temperature", value: "-20°C ~ 180°C" },
      { label: "Pressure", value: "≤ 0.8 MPa" },
      { label: "Speed", value: "≤ 3000 rpm" },
    ],
    commonSizes: [
      { label: "Inner Dia (d)", value: "10 ~ 70 mm" },
      { label: "Outer Dia (D)", value: "22 ~ 90 mm" },
      { label: "Height (H)", value: "6 ~ 16 mm" },
    ],
    matingMaterials: ["Silicon Carbide (SiC)", "Tungsten Carbide (WC)", "Stainless Steel"],
    installationNotes: [
      "Confirm model matches equipment before installation",
      "Inspect seal face for damage",
      "Use dedicated tool for pressing; maintain concentricity",
      "Avoid over-compressing the spring",
      "Hand-rotate to check rotational freedom before operation",
    ],
    applications: ["Industrial Pumps", "Agitators", "Rotating Equipment", "Light Machinery"],
    materials: ["Standard Graphite", "Resin-Impregnated Graphite", "Antimony-Impregnated Graphite", "Copper-Impregnated Graphite"],
    features: ["Compact structure", "Reliable sealing", "Easy installation", "Cost-effective"],
    faq: [],
    image: "/images/products/catalog/f-type.jpg",
  },
  {
    slug: "120-m3n-series",
    name: "120 (M3N) Carbon Graphite Seal Ring",
    model: "120 (M3N) Series",
    category: "碳石墨密封环",
    description:
      "The 120 (M3N) carbon graphite seal ring features a multi-spring design with excellent compensation ability and follow-up performance. Suitable for shaft sealing in centrifugal pumps, chemical pumps, and other rotating equipment, operating stably under various media conditions.",
    shortDesc: "Multi-spring carbon graphite seal ring, strong compensation capability.",
    specs: [
      { label: "Model", value: "120 (M3N)" },
      { label: "Temperature", value: "-20°C ~ 200°C" },
      { label: "Pressure", value: "≤ 1.2 MPa" },
      { label: "Speed", value: "≤ 3500 rpm" },
    ],
    commonSizes: [
      { label: "Inner Dia (d)", value: "14 ~ 90 mm" },
      { label: "Outer Dia (D)", value: "28 ~ 120 mm" },
      { label: "Height (H)", value: "8 ~ 22 mm" },
    ],
    matingMaterials: ["Silicon Carbide (SiC)", "Tungsten Carbide (WC)", "Stainless Steel"],
    installationNotes: [
      "Multi-spring design: ensure all springs are at equal height",
      "Clean seal cavity before installation; remove contaminants",
      "Gently wipe seal face before assembly; avoid impacts",
      "Tighten bolts diagonally to recommended torque",
      "Purge air from seal cavity before operation",
    ],
    applications: ["Centrifugal Pumps", "Chemical Pumps", "Agitators", "General Industry"],
    materials: ["Standard Graphite", "Resin-Impregnated Graphite", "Antimony-Impregnated Graphite", "Copper-Impregnated Graphite"],
    features: ["Multi-spring compensation", "Good follow-up performance", "Wide application range", "Stable sealing"],
    faq: [],
    image: "/images/products/catalog/120-m3n.jpg",
  },
  {
    slug: "fbd-series",
    name: "FBD Carbon Graphite Seal Ring",
    model: "FBD Series",
    category: "碳石墨密封环",
    description:
      "The FBD carbon graphite seal ring is a specialized model for specific pump types and sealing device applications. Standardized interface dimensions and optimized carbon graphite material ensure long-term sealing performance under rated operating conditions.",
    shortDesc: "FBD carbon graphite seal ring, specialized model for pump matching.",
    specs: [
      { label: "Model", value: "FBD" },
      { label: "Temperature", value: "-20°C ~ 180°C" },
      { label: "Pressure", value: "≤ 0.8 MPa" },
      { label: "Speed", value: "≤ 3000 rpm" },
    ],
    commonSizes: [
      { label: "Inner Dia (d)", value: "12 ~ 80 mm" },
      { label: "Outer Dia (D)", value: "24 ~ 100 mm" },
      { label: "Height (H)", value: "6 ~ 18 mm" },
    ],
    matingMaterials: ["Silicon Carbide (SiC)", "Tungsten Carbide (WC)", "Stainless Steel"],
    installationNotes: [
      "Verify model and dimensions match original seal before installation",
      "Clean seal face and gently assemble",
      "Apply even press force; avoid uneven loading",
      "Adjust spring compression per standard",
      "Monitor leakage during initial operation",
    ],
    applications: ["Pump Matching", "Industrial Sealing", "Rotating Equipment", "Specialized Machinery"],
    materials: ["Standard Graphite", "Resin-Impregnated Graphite", "Antimony-Impregnated Graphite", "Copper-Impregnated Graphite"],
    features: ["Specialized model matching", "Standardized interface", "Reliable sealing", "Long service life"],
    faq: [],
    image: "/images/products/catalog/fbd.jpg",
  },
  {
    slug: "2100-series",
    name: "2100 Carbon Graphite Seal Ring",
    model: "2100 Series",
    category: "碳石墨密封环",
    description:
      "The 2100 carbon graphite seal ring is a mechanical seal ring designed for medium-sized rotating equipment. The structural design optimizes load distribution, maintaining stable sealing performance under medium to high-speed operating conditions. Suitable for various industrial pumps and compressors.",
    shortDesc: "Medium-duty carbon graphite seal ring for medium-high speed conditions.",
    specs: [
      { label: "Model", value: "2100" },
      { label: "Temperature", value: "-20°C ~ 200°C" },
      { label: "Pressure", value: "≤ 1.0 MPa" },
      { label: "Speed", value: "≤ 4000 rpm" },
    ],
    commonSizes: [
      { label: "Inner Dia (d)", value: "16 ~ 90 mm" },
      { label: "Outer Dia (D)", value: "30 ~ 120 mm" },
      { label: "Height (H)", value: "8 ~ 22 mm" },
    ],
    matingMaterials: ["Silicon Carbide (SiC)", "Tungsten Carbide (WC)", "Stainless Steel", "Ceramic"],
    installationNotes: [
      "Confirm dimensions match installation space before installation",
      "Never bump the seal face",
      "Use dedicated pressing tool for installation accuracy",
      "Adjust spring compression per standard",
      "Monitor temperature and vibration during operation",
    ],
    applications: ["Industrial Pumps", "Compressors", "Agitators", "General Rotating Equipment"],
    materials: ["Standard Graphite", "Resin-Impregnated Graphite", "Antimony-Impregnated Graphite", "Copper-Impregnated Graphite"],
    features: ["Optimized structural design", "Good medium-high speed performance", "Stable sealing", "Excellent durability"],
    faq: [],
    image: "/images/products/catalog/2100.jpg",
  },
  {
    slug: "1527-series",
    name: "1527 Carbon Graphite Seal Ring",
    model: "1527 Series",
    category: "碳石墨密封环",
    description:
      "The 1527 carbon graphite seal ring is a specific model mechanical seal ring with standardized dimensions for interchangeability with equivalent models. Precision-lapped carbon graphite seal faces ensure low leakage rates and long service life.",
    shortDesc: "1527 carbon graphite seal ring, standardized interchangeable design.",
    specs: [
      { label: "Model", value: "1527" },
      { label: "Temperature", value: "-20°C ~ 180°C" },
      { label: "Pressure", value: "≤ 0.8 MPa" },
      { label: "Speed", value: "≤ 3500 rpm" },
    ],
    commonSizes: [
      { label: "Inner Dia (d)", value: "12 ~ 80 mm" },
      { label: "Outer Dia (D)", value: "24 ~ 100 mm" },
      { label: "Height (H)", value: "6 ~ 18 mm" },
    ],
    matingMaterials: ["Silicon Carbide (SiC)", "Tungsten Carbide (WC)", "Stainless Steel"],
    installationNotes: [
      "Compare dimensions with original seal to confirm compatibility",
      "Wipe seal face with clean soft cloth",
      "Maintain even pressure and perpendicularity when pressing",
      "Adjust spring per requirements",
      "Gradually load to rated conditions during initial operation",
    ],
    applications: ["Industrial Pumps", "General Equipment", "Sealing Matching", "Rotating Machinery"],
    materials: ["Standard Graphite", "Resin-Impregnated Graphite", "Antimony-Impregnated Graphite", "Copper-Impregnated Graphite"],
    features: ["Standardized interchangeable dimensions", "Low leakage rate", "Long life", "Consistent quality"],
    faq: [],
    image: "/images/products/catalog/1527.jpg",
  },
  {
    slug: "us-series",
    name: "US Carbon Graphite Seal Ring",
    model: "US Series",
    category: "碳石墨密封环",
    description:
      "The US carbon graphite seal ring features a standard interface design suitable for shaft sealing in various conventional pump types and rotating equipment. Carbon graphite material with precision-lapped faces provides stable and reliable sealing in clean water, oils, and mildly corrosive media.",
    shortDesc: "US carbon graphite seal ring, general-purpose shaft seal.",
    specs: [
      { label: "Model", value: "US" },
      { label: "Temperature", value: "-20°C ~ 200°C" },
      { label: "Pressure", value: "≤ 0.8 MPa" },
      { label: "Speed", value: "≤ 3500 rpm" },
    ],
    commonSizes: [
      { label: "Inner Dia (d)", value: "10 ~ 80 mm" },
      { label: "Outer Dia (D)", value: "22 ~ 100 mm" },
      { label: "Height (H)", value: "6 ~ 18 mm" },
    ],
    matingMaterials: ["Silicon Carbide (SiC)", "Tungsten Carbide (WC)", "Stainless Steel"],
    installationNotes: [
      "Confirm specifications match installation equipment before installation",
      "Clean seal face and gently assemble",
      "Check compression after spring seat installation",
      "Use guide sleeve for perpendicularity when pressing",
      "Hand-rotate to check freedom before operation",
    ],
    applications: ["Industrial Pumps", "Water Pumps", "Light Equipment", "General Sealing"],
    materials: ["Standard Graphite", "Resin-Impregnated Graphite", "Antimony-Impregnated Graphite", "Copper-Impregnated Graphite"],
    features: ["Standard interface design", "Easy replacement", "Stable performance", "Cost-effective"],
    faq: [],
    image: "/images/products/catalog/us.jpg",
  },
  {
    slug: "527-series",
    name: "527 Carbon Graphite Seal Ring",
    model: "527 Series",
    category: "碳石墨密封环",
    description:
      "The 527 carbon graphite seal ring is a standard model interchangeable with equivalent models. Precision-machined from premium carbon graphite material with high-precision face lapping, ensuring reliable sealing under various media conditions.",
    shortDesc: "527 carbon graphite seal ring, standard interchangeable seal ring.",
    specs: [
      { label: "Model", value: "527" },
      { label: "Temperature", value: "-20°C ~ 180°C" },
      { label: "Pressure", value: "≤ 0.8 MPa" },
      { label: "Speed", value: "≤ 3000 rpm" },
    ],
    commonSizes: [
      { label: "Inner Dia (d)", value: "10 ~ 70 mm" },
      { label: "Outer Dia (D)", value: "22 ~ 90 mm" },
      { label: "Height (H)", value: "6 ~ 16 mm" },
    ],
    matingMaterials: ["Silicon Carbide (SiC)", "Tungsten Carbide (WC)", "Stainless Steel"],
    installationNotes: [
      "Confirm model and dimensions match before installation",
      "Clean seal face and gently wipe; avoid scratches",
      "Apply even press force; use dedicated tool",
      "Adjust spring compression per standard",
      "Check leakage and temperature during initial run",
    ],
    applications: ["Industrial Pumps", "Sealing Matching", "General Equipment", "Rotating Machinery"],
    materials: ["Standard Graphite", "Resin-Impregnated Graphite", "Antimony-Impregnated Graphite", "Copper-Impregnated Graphite"],
    features: ["Standard interchangeable dimensions", "Precision-lapped face", "Reliable sealing", "Prompt delivery"],
    faq: [],
    image: "/images/products/catalog/527.jpg",
  },
  {
    slug: "press-series",
    name: "Press Seal Ring",
    model: "Press Series",
    category: "碳石墨密封环",
    description:
      "The press seal ring is specially designed for high-pressure equipment such as presses, die-casting machines, and hydraulic presses. Made from high-strength carbon graphite material with excellent pressure resistance and self-lubricating properties, maintaining stable sealing under heavy load conditions. Suitable for hydraulic systems and high-pressure reciprocating motion applications.",
    shortDesc: "High-pressure press carbon graphite seal ring, pressure-resistant and self-lubricating.",
    specs: [
      { label: "Model", value: "Press Series (custom per drawing)" },
      { label: "Temperature", value: "-20°C ~ 250°C" },
      { label: "Pressure", value: "≤ 15 MPa" },
      { label: "Speed", value: "≤ 2000 rpm" },
      { label: "Medium", value: "Hydraulic oil, water, emulsion" },
    ],
    commonSizes: [
      { label: "Inner Dia (d)", value: "20 ~ 120 mm" },
      { label: "Outer Dia (D)", value: "36 ~ 150 mm" },
      { label: "Height (H)", value: "10 ~ 30 mm" },
    ],
    matingMaterials: ["Silicon Carbide (SiC)", "Tungsten Carbide (WC)", "Hardened Stainless Steel", "Ductile Iron"],
    installationNotes: [
      "Confirm seal face integrity before installation for high-pressure applications",
      "Clean installation cavity thoroughly; remove burrs",
      "Use dedicated pressing tool to ensure seal ring is properly seated",
      "Purge air from hydraulic system lines after connection",
      "Gradually increase pressure to rated working pressure during initial operation",
    ],
    applications: ["Presses", "Die-Casting Machines", "Hydraulic Presses", "High-Pressure Reciprocating Pumps"],
    materials: ["High-Strength Graphite", "Antimony-Impregnated Graphite", "Copper-Impregnated Graphite"],
    features: ["High pressure resistance", "Excellent self-lubrication", "High temperature resistance", "Suitable for heavy-load conditions"],
    faq: [],
    image: "/images/products/catalog/press.jpg",
  },
  {
    slug: "dyeing-machine-series",
    name: "Dyeing Machine 41.275 Seal Ring",
    model: "Dyeing Machine 41.275 Series",
    category: "碳石墨密封环",
    description:
      "The dyeing machine 41.275 seal ring is specially designed for textile dyeing machinery, suitable for shaft sealing of dyeing machine pump units and agitator devices. Made from corrosion-resistant carbon graphite material for long-term stable operation in high-temperature dye liquor and chemical environments. An ideal sealing choice for textile industry dyeing equipment.",
    shortDesc: "Dyeing machine carbon graphite seal ring, high-temp dye-liquor corrosion resistant.",
    specs: [
      { label: "Model", value: "41.275 (custom per drawing)" },
      { label: "Temperature", value: "-10°C ~ 180°C" },
      { label: "Pressure", value: "≤ 0.8 MPa" },
      { label: "Speed", value: "≤ 3000 rpm" },
      { label: "Medium", value: "Dye liquor, chemicals, hot water" },
    ],
    commonSizes: [
      { label: "Inner Dia (d)", value: "16 ~ 70 mm" },
      { label: "Outer Dia (D)", value: "30 ~ 95 mm" },
      { label: "Height (H)", value: "8 ~ 18 mm" },
    ],
    matingMaterials: ["Silicon Carbide (SiC)", "Tungsten Carbide (WC)", "Stainless Steel (316L)"],
    installationNotes: [
      "Confirm model matches dyeing machine before installation",
      "Clean seal face and gently wipe; never use hard objects",
      "Use O-rings made of high-temperature and chemical-resistant material",
      "Use dedicated tool for pressing to ensure installation accuracy",
      "Regularly check seal cavity temperature and leakage during operation",
    ],
    applications: ["Dyeing Machines", "Textile Equipment", "Dye Pumps", "Agitator Units"],
    materials: ["Standard Graphite", "Resin-Impregnated Graphite", "Antimony-Impregnated Graphite"],
    features: ["Dye liquor corrosion resistant", "High temperature resistant", "Long service life", "Textile industry specialized"],
    faq: [],
    image: "/images/products/catalog/dyeing-machine.jpg",
  },
]
